version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - React
      - build:
          requires:
            - React
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main        

jobs:
  React:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
     

  build:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build
          command: npm run build       